### ISSUE TITLE
Harberger Tax NFT -- RadicalxChange Working Group

### ISSUE THREAD

**Issue by erichfi** [rugpullindex/libharberger#1]
Gm @TimDaub,

It's great to see you're working on Harberger Tax NFTs -- RadicalxChange is currently organizing a working group around this topic, connecting people working on it in regular meetings. The next meeting happens tomorrow at 4 pm UTC.

Shoot me an email at leon@radicalxchange.org if you'll be available to join us. I would be delighted if you presented your work at the meeting.

In any case, we should catch up in the #salsa channel of the RadicalxChange Discord, where the working group is primarily coordinating outside the meetings: https://discord.gg/HF8rmjHpyf. Salsa is another acronym for the Harberger tax mechanism: Self-Assessed Licences Sold at Auction.

Best,
Leon

**Comment by TimDaub** [comment]
hey @leoneric thanks for making me aware of the group and Discord. I've joined both and I want to continue contributing. For now, I'll close this issue as I feel like I've acted upon it accordingly.
